### ISSUE TITLE
Было бы круто если бы ты это добавил из коробки

### ISSUE THREAD

**Issue by ciricc** [iSa1vatore/vk-mini-app-boilerplate#1]
Этот реп - уже находка, но мне кажется тут не хватает примера как сохранить состояние форм при переключении через setStory. Панели сохраняет, скролл сохраняет и т.д, но вот формы не сохраняет) Чисто на свое усмотрение добавь, если хочешь

**Comment by iSa1vatore** [comment]
Добавил, работает на вкладке examples 2 в модальном окне.

Заюзал хранилище редакса, это подходит если приложение хоть немного сложное, если всего одна форма, то можно не запариваться и поместить значения стейта в тот же localStorage.

**Comment by ciricc** [comment]
Да не, редакс тут как раз) Спасибо за такой классный реп
