### ISSUE TITLE
Еще полезная и прикольная фитча (просьба)

### ISSUE THREAD

**Issue by ciricc** [iSa1vatore/vk-mini-app-boilerplate#2]
Опять по твоему желанию)

Вертикальный скролл сохраняет, но нет API для сохранения горизонтального скролла внутренних компонентов. А было бы удобно) Ну то есть onscroll мы реализует сами, а сохранение происходит в основном storage где-нибудь в componentScrolls[componentId].(x,y)

**Comment by iSa1vatore** [comment]
Добавил, дока в README.

**Comment by ciricc** [comment]
Отлично!) Спасибо
