### ISSUE TITLE
Цвет текста в PanelHeader не соответствует цветовой схеме VK Me

### ISSUE THREAD

**Issue by egorprnn** [iSa1vatore/vk-mini-app-boilerplate#4]
![Sample](https://sun9-7.userapi.com/c850136/v850136936/1b742e/d3hV_ix3fxg.jpg)

**Comment by iSa1vatore** [comment]
Не совсем понял что там чему не соответствует, но к моей репе это не имеет отношения.
VKUI: https://github.com/VKCOM/VKUI

**Comment by egorprnn** [comment]
Вроде текст в PanelHeader должен быть голубого оттенка, как в самом приложении VK Me, все же, это проблема VK-UI?

**Comment by iSa1vatore** [comment]
Да.
