### ISSUE TITLE
Проверка на action.payload.from === 'Android' не дает возвращаться назад при cross-tab навигации на iOS

### ISSUE THREAD

**Issue by abaranovskii** [iSa1vatore/vk-mini-app-boilerplate#7]
В некоторых случаях в приложении необходимо перейти из панели на одной табе в панель на другой табе. Это можно сделать с помощью `this.props.setStoty(“more”, “more”);`. Однако, если мы открываем приложение и сразу переходим на панель в другой табе и хотим вернуться назад с помощью `this.props.goBack()`, то из-за [этой ](https://github.com/iSa1vatore/vk-mini-app-boilerplate/blob/master/src/js/store/router/reducers.js#L197) проверки, на iOS это работать не будет.

Я попробовал отключить эту проверку на Android и не заметил каких-либо проблем с навигацией в приложении. Не думаю, что эта проверка нужна.

**Comment by iSa1vatore** [comment]
Fix
