### ISSUE TITLE
Некорректная анимация перехода панелей в режиме "модальные окна"

### ISSUE THREAD

**Issue by abaranovskii** [iSa1vatore/vk-mini-app-boilerplate#8]
![Profile-20200124T202648](https://user-images.githubusercontent.com/5149090/73090551-9ec16d00-3ee9-11ea-9cfa-4c63533fe9a9.gif)

Проблема в том, что при переходе из одной панели одного view в панель другого view, `activePanel` [меняется ](https://github.com/iSa1vatore/vk-mini-app-boilerplate/blob/master/src/App.js#L110)для обоих. 

В [примере](https://vkcom.github.io/vkui-styleguide/#root) из официальной документации такого эфекта не происходит т.к у каждой View всегда один и тот же `activePanel`

```
<Root activeView={this.state.activeView}>
        <View activePanel="panel1.1" id="view1">
          <Panel id="panel1.1">
            <PanelHeader>View 1</PanelHeader>
            <Group>
              <CellButton onClick={ () => this.setState({ activeView: 'view2' }) }>
                Open View 2
              </CellButton>
            </Group>
          </Panel>
        </View>
        <View header activePanel="panel2.1" id="view2">
          <Panel id="panel2.1">
            <PanelHeader>View 2</PanelHeader>
            <Group>
              <CellButton onClick={ () => this.setState({ activeView: 'view1' }) }>
                Back to View 1
              </CellButton>
            </Group>
          </Panel>
        </View>
      </Root>
```

Возможно придется создавать доп. хранилище активных панелей или что-нибудь ещё

**Comment by iSa1vatore** [comment]
Fix.
